import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Link } from "./link";
import Nav from "./nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />

        <main className="m-4">{children}</main>
      </body>
    </html>
  );
}
