import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Link from "next/link";
import { Link } from "./link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-2 m-2">
          <Link
            className="px-3 py-2 rounded data-[state=active]:bg-blue-500 data-[state=active]:text-white"
            href="/"
          >
            Home
          </Link>
          <Link
            className="px-3 py-2 rounded data-[state=active]:bg-blue-500 data-[state=active]:text-white"
            href="/page-1"
          >
            Page 1
          </Link>
          <Link
            className="px-3 py-2 rounded data-[state=active]:bg-blue-500 data-[state=active]:text-white"
            href="/page-2"
          >
            Page 2
          </Link>
        </nav>

        <main className="m-4">{children}</main>
      </body>
    </html>
  );
}
